import {
    createDocumentId,
    createTimestampPair,
    normalizeRequiredString,
} from "./model-helpers.js";

export const ACCOUNT_ROLES = Object.freeze(["customer", "admin"]);

function normalizeAccountRole(value, fieldName = "role") {
    const normalizedValue = normalizeRequiredString(value, fieldName);

    if (!ACCOUNT_ROLES.includes(normalizedValue)) {
        throw new Error(
            `Account requires ${fieldName} to be one of: ${ACCOUNT_ROLES.join(", ")}`
        );
    }

    return normalizedValue;
}

export const ACCOUNT_DOCUMENT_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createAccount()",
        description: "MongoDB technical identifier for the account document.",
    },
    accountId: {
        type: "string",
        required: true,
        description: "Stable internal identity used across modules and auth tokens.",
    },
    email: {
        type: "string",
        required: true,
        description: "Normalized unique login identifier.",
    },
    passwordHash: {
        type: "string",
        required: true,
        description: "Hashed password used by auth verification.",
    },
    role: {
        type: "string",
        required: true,
        enum: ACCOUNT_ROLES,
        description: "Persisted system role for the account.",
    },
    createdAt: {
        type: "date",
        required: true,
        default: "generated by createAccount()",
        description: "Account creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: true,
        default: "mirrors createdAt unless overridden",
        description: "Account update timestamp.",
    },
});

export function createAccount(input = {}) {
    const { createdAt, updatedAt } = createTimestampPair(input);

    return {
        _id: createDocumentId(input._id, "_id"),
        accountId: normalizeRequiredString(input.accountId, "accountId"),
        email: normalizeRequiredString(input.email, "email"),
        passwordHash: normalizeRequiredString(input.passwordHash, "passwordHash"),
        role: normalizeAccountRole(input.role, "role"),
        createdAt,
        updatedAt,
    };
}

