services:
  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    image: node:24-bookworm-slim
    container_name: backend
    env_file:
      - ./apps/backend/.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/fyp-retail-system
      NODE_ENV: development
      PNPM_STORE_DIR: /app/.pnpm-store
      CI: "true"
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./apps/backend:/app/apps/backend
      - pnpm_store:/app/.pnpm-store
      - root_node_modules:/app/node_modules
      - backend_node_modules:/app/apps/backend/node_modules
    command:
      - /bin/bash
      - -lc
      - corepack enable && pnpm install --filter @apps/backend && pnpm --filter @apps/backend dev
    restart: unless-stopped

  frontend:
    image: node:24-bookworm-slim
    container_name: frontend
    environment:
      NODE_ENV: development
      PNPM_STORE_DIR: /app/.pnpm-store
      CI: "true"
    depends_on:
      - backend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./apps/frontend:/app/apps/frontend
      - pnpm_store:/app/.pnpm-store
      - root_node_modules:/app/node_modules
      - frontend_node_modules:/app/apps/frontend/node_modules
    command:
      - /bin/bash
      - -lc
      - corepack enable && pnpm install --filter @apps/frontend && pnpm --filter @apps/frontend exec vite --host 0.0.0.0 --port 5173
    restart: unless-stopped

volumes:
  mongo_data:
  pnpm_store:
  root_node_modules:
  backend_node_modules:
  frontend_node_modules:
