import {
    createDocumentId,
    createTimestampPair,
    normalizeBoolean,
    normalizeDate,
    normalizeOwnerType,
    normalizePositiveInteger,
    normalizeRequiredObjectId,
    normalizeRequiredString,
} from "./model-helpers.js";

export const CART_ITEM_DOCUMENT_SHAPE = Object.freeze({
    variantId: {
        type: "ObjectId",
        required: true,
        description: "Catalog variant identifier stored in the cart line.",
    },
    quantity: {
        type: "number",
        required: true,
        description: "Requested quantity for the cart line.",
    },
    selected: {
        type: "boolean",
        required: true,
        default: true,
        description: "Checkout selection flag persisted per cart line.",
    },
    addedAt: {
        type: "date",
        required: true,
        default: "generated by createCartItem()",
        description: "Timestamp for when the line first entered the cart.",
    },
});

export const CART_DOCUMENT_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createCart()",
        description: "MongoDB technical identifier for the cart document.",
    },
    ownerType: {
        type: "string",
        required: true,
        description: "Owner discriminator, for example guest or customer.",
    },
    ownerKey: {
        type: "string",
        required: true,
        description: "Stable owner identifier, cookie-backed for guests.",
    },
    items: {
        type: "array",
        required: true,
        description: "Persisted cart lines.",
    },
    createdAt: {
        type: "date",
        required: true,
        default: "generated by createCart()",
        description: "Cart creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: true,
        default: "mirrors createdAt unless overridden",
        description: "Cart update timestamp.",
    },
});

export function createCartItem(input = {}) {
    const addedAt = normalizeDate(input.addedAt, "addedAt", new Date());

    return {
        variantId: normalizeRequiredObjectId(input.variantId, "variantId"),
        quantity: normalizePositiveInteger(input.quantity, "quantity"),
        selected: normalizeBoolean(input.selected, "selected", true),
        addedAt,
    };
}

export function createCart(input = {}) {
    const { createdAt, updatedAt } = createTimestampPair(input);
    const items = Array.isArray(input.items) ? input.items : [];

    return {
        _id: createDocumentId(input._id, "_id"),
        ownerType: normalizeOwnerType(input.ownerType),
        ownerKey: normalizeRequiredString(input.ownerKey, "ownerKey"),
        items: items.map((item) => createCartItem(item)),
        createdAt,
        updatedAt,
    };
}
