import { DEFAULT_LOW_STOCK_THRESHOLD } from "../constants/index.js";
import {
    createDocumentId,
    createTimestampPair,
    normalizeNonNegativeInteger,
    normalizeRequiredObjectId,
} from "./model-helpers.js";

export const INVENTORY_DOCUMENT_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createInventoryRecord()",
        description: "MongoDB technical identifier for the inventory document.",
    },
    variantId: {
        type: "ObjectId",
        required: true,
        description: "Catalog variant identifier tracked by inventory at SKU level.",
    },
    stockQuantity: {
        type: "number",
        required: true,
        description: "Current available stock quantity for the variant.",
    },
    lowStockThreshold: {
        type: "number",
        required: true,
        default: DEFAULT_LOW_STOCK_THRESHOLD,
        description: "Threshold used to classify the variant as low stock.",
    },
    createdAt: {
        type: "date",
        required: true,
        default: "generated by createInventoryRecord()",
        description: "Inventory record creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: true,
        default: "mirrors createdAt unless overridden",
        description: "Inventory record update timestamp.",
    },
});

export function createInventoryRecord(input = {}) {
    const { createdAt, updatedAt } = createTimestampPair(input);

    return {
        _id: createDocumentId(input._id, "_id"),
        variantId: normalizeRequiredObjectId(input.variantId, "variantId"),
        stockQuantity: normalizeNonNegativeInteger(
            input.stockQuantity,
            "stockQuantity"
        ),
        lowStockThreshold: normalizeNonNegativeInteger(
            input.lowStockThreshold,
            "lowStockThreshold",
            DEFAULT_LOW_STOCK_THRESHOLD
        ),
        createdAt,
        updatedAt,
    };
}
