import {
    createDocumentId,
    createTimestampPair,
    normalizeOptionalString,
    normalizeRequiredString,
} from "./model-helpers.js";

export const BRAND_STATUSES = Object.freeze(["active", "inactive"]);

export const BRAND_DOCUMENT_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createBrand()",
        description: "MongoDB technical identifier for the brand document.",
    },
    code: {
        type: "string",
        required: true,
        description: "Unique business key used for CSV import, mapping, and lookup.",
    },
    name: {
        type: "string",
        required: true,
        description: "Human-readable brand name.",
    },
    description: {
        type: "string",
        required: false,
        default: null,
        description: "Optional brand description for admin-facing catalog metadata.",
    },
    status: {
        type: "string",
        required: true,
        default: "active",
        enum: BRAND_STATUSES,
        description: "Business lifecycle status for the brand reference entity.",
    },
    createdAt: {
        type: "date",
        required: true,
        default: "generated by createBrand()",
        description: "Brand creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: true,
        default: "mirrors createdAt unless overridden",
        description: "Brand update timestamp.",
    },
});

export function createBrand(input = {}) {
    const { createdAt, updatedAt } = createTimestampPair(input);

    return {
        _id: createDocumentId(input._id, "_id"),
        code: normalizeRequiredString(input.code, "code"),
        name: normalizeRequiredString(input.name, "name"),
        description: normalizeOptionalString(input.description, "description"),
        status: normalizeBrandStatus(input.status),
        createdAt,
        updatedAt,
    };
}

function normalizeBrandStatus(value) {
    const normalizedStatus = value === undefined ? "active" : value;

    if (!BRAND_STATUSES.includes(normalizedStatus)) {
        throw new Error(
            `Catalog brand status must be one of: ${BRAND_STATUSES.join(", ")}`
        );
    }

    return normalizedStatus;
}
