import {
    createDocumentId,
    createTimestampPair,
    normalizeOptionalString,
    normalizeRequiredString,
} from "./model-helpers.js";

export const CATEGORY_STATUSES = Object.freeze(["active", "inactive"]);

export const CATEGORY_DOCUMENT_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createCategory()",
        description: "MongoDB technical identifier for the category document.",
    },
    code: {
        type: "string",
        required: true,
        description: "Unique business key used for CSV import, mapping, and lookup.",
    },
    name: {
        type: "string",
        required: true,
        description: "Human-readable category name.",
    },
    description: {
        type: "string",
        required: false,
        default: null,
        description: "Optional admin-facing description for the category.",
    },
    status: {
        type: "string",
        required: true,
        default: "active",
        enum: CATEGORY_STATUSES,
        description: "Business lifecycle status for the category reference entity.",
    },
    createdAt: {
        type: "date",
        required: true,
        default: "generated by createCategory()",
        description: "Category creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: true,
        default: "mirrors createdAt unless overridden",
        description: "Category update timestamp.",
    },
});

export function createCategory(input = {}) {
    const { createdAt, updatedAt } = createTimestampPair(input);

    return {
        _id: createDocumentId(input._id, "_id"),
        code: normalizeRequiredString(input.code, "code"),
        name: normalizeRequiredString(input.name, "name"),
        description: normalizeOptionalString(input.description, "description"),
        status: normalizeCategoryStatus(input.status),
        createdAt,
        updatedAt,
    };
}

function normalizeCategoryStatus(value) {
    const normalizedStatus = value === undefined ? "active" : value;

    if (!CATEGORY_STATUSES.includes(normalizedStatus)) {
        throw new Error(
            `Catalog category status must be one of: ${CATEGORY_STATUSES.join(", ")}`
        );
    }

    return normalizedStatus;
}
