import {
    createDocumentId,
    createTimestampPair,
    normalizeNonNegativeInteger,
    normalizeRequiredObjectId,
    normalizeRequiredString,
} from "./model-helpers.js";

const ALLOWED_PRODUCT_MEDIA_MIME_TYPES = Object.freeze([
    "image/jpeg",
    "image/png",
    "image/webp",
]);

export const PRODUCT_MEDIA_METADATA_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createProductMediaMetadata()",
        description: "MongoDB technical identifier for image metadata.",
    },
    productId: {
        type: "ObjectId",
        required: true,
        description: "Required product reference stored as a MongoDB ObjectId.",
    },
    variantId: {
        type: "ObjectId",
        required: true,
        description:
            "Required variant reference stored as a MongoDB ObjectId because images are attached at variant level.",
    },
    url: {
        type: "string",
        required: true,
        description: "Resolvable access URL of an already uploaded image file.",
    },
    storagePath: {
        type: "string",
        required: true,
        description: "Bucket object path used for traceability and future deletion.",
    },
    fileName: {
        type: "string",
        required: true,
        description: "Stored file name in Firebase Storage.",
    },
    mimeType: {
        type: "string",
        required: true,
        enum: ALLOWED_PRODUCT_MEDIA_MIME_TYPES,
        description: "Image MIME type. Binary content is stored outside MongoDB.",
    },
    size: {
        type: "number",
        required: true,
        description: "Image file size in bytes.",
    },
    sortOrder: {
        type: "number",
        required: false,
        default: 0,
        description: "Optional display order for variant galleries.",
    },
    createdAt: {
        type: "date",
        required: true,
        description: "Metadata creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: false,
        description: "Metadata update timestamp.",
    },
});

export const PRODUCT_MEDIA_BINARY_FIELDS = Object.freeze([
    "binary",
    "buffer",
    "base64",
    "data",
]);

export function createProductMediaMetadata({
    _id,
    productId,
    variantId,
    url,
    storagePath,
    fileName,
    mimeType,
    size,
    sortOrder = 0,
    createdAt = new Date(),
    updatedAt,
} = {}) {
    const timestamps = createTimestampPair({ createdAt, updatedAt });

    assertAllowedMimeType(mimeType);
    assertFileSize(size);

    const mediaDocument = {
        _id: createDocumentId(_id, "_id"),
        productId: normalizeRequiredObjectId(productId, "productId"),
        variantId: normalizeRequiredObjectId(variantId, "variantId"),
        url: normalizeRequiredString(url, "url"),
        storagePath: normalizeRequiredString(storagePath, "storagePath"),
        fileName: normalizeRequiredString(fileName, "fileName"),
        mimeType,
        size,
        sortOrder: normalizeSortOrder(sortOrder),
        createdAt: timestamps.createdAt,
    };

    if (updatedAt !== undefined) {
        mediaDocument.updatedAt = timestamps.updatedAt;
    }

    return mediaDocument;
}

function assertAllowedMimeType(value) {
    normalizeRequiredString(value, "mimeType");

    if (!ALLOWED_PRODUCT_MEDIA_MIME_TYPES.includes(value)) {
        throw new Error(
            `Catalog media metadata mimeType must be one of: ${ALLOWED_PRODUCT_MEDIA_MIME_TYPES.join(", ")}`
        );
    }
}

function assertFileSize(value) {
    normalizeNonNegativeInteger(value, "size");
}

function normalizeSortOrder(value) {
    return normalizeNonNegativeInteger(value, "sortOrder", 0);
}

export function getAllowedProductMediaMimeTypes() {
    return [...ALLOWED_PRODUCT_MEDIA_MIME_TYPES];
}
