import {
    createDocumentId,
    createTimestampPair,
    normalizeOptionalString,
    normalizeRequiredString,
} from "./model-helpers.js";

export const TAG_STATUSES = Object.freeze(["active", "inactive"]);

export const TAG_DOCUMENT_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createTag()",
        description: "MongoDB technical identifier for the tag document.",
    },
    code: {
        type: "string",
        required: true,
        description: "Unique business key used for CSV import, mapping, and lookup.",
    },
    name: {
        type: "string",
        required: true,
        description: "Human-readable tag name.",
    },
    description: {
        type: "string",
        required: false,
        default: null,
        description: "Optional admin-facing description for the tag.",
    },
    status: {
        type: "string",
        required: true,
        default: "active",
        enum: TAG_STATUSES,
        description: "Business lifecycle status for the tag reference entity.",
    },
    createdAt: {
        type: "date",
        required: true,
        default: "generated by createTag()",
        description: "Tag creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: true,
        default: "mirrors createdAt unless overridden",
        description: "Tag update timestamp.",
    },
});

export function createTag(input = {}) {
    const { createdAt, updatedAt } = createTimestampPair(input);

    return {
        _id: createDocumentId(input._id, "_id"),
        code: normalizeRequiredString(input.code, "code"),
        name: normalizeRequiredString(input.name, "name"),
        description: normalizeOptionalString(input.description, "description"),
        status: normalizeTagStatus(input.status),
        createdAt,
        updatedAt,
    };
}

function normalizeTagStatus(value) {
    const normalizedStatus = value === undefined ? "active" : value;

    if (!TAG_STATUSES.includes(normalizedStatus)) {
        throw new Error(`Catalog tag status must be one of: ${TAG_STATUSES.join(", ")}`);
    }

    return normalizedStatus;
}
