import {
    assertVariantPricingInvariant,
} from "../utils/catalog-invariants.js";
import { normalizeSku } from "../utils/catalog-field-normalizers.js";
import {
    createDocumentId,
    createSoftDeleteState,
    createTimestampPair,
    normalizeBoolean,
    normalizeNonNegativeInteger,
    normalizeNonNegativeNumber,
    normalizeObjectIdList,
    normalizeOptionalString,
    normalizeRequiredObjectId,
    normalizeRequiredString,
} from "./model-helpers.js";

export const VARIANT_STATUSES = Object.freeze(["active", "inactive"]);

export const VARIANT_ATTRIBUTES_SHAPE = Object.freeze({
    ram: {
        type: "string",
        required: true,
        description: "Variant-level RAM option. Must not be stored in product specs.",
    },
    rom: {
        type: "string",
        required: true,
        description: "Variant-level storage option. Must not be stored in product specs.",
    },
    color: {
        type: "string",
        required: true,
        description: "Variant-level color option. Must not be stored in product specs.",
    },
    colorFullName: {
        type: "string",
        required: false,
        default: null,
        description:
            "Optional marketing/full color name preserved for richer display contexts such as tooltips.",
    },
});

export const VARIANT_VIDEO_SHAPE = Object.freeze({
    url: {
        type: "string",
        required: true,
        description: "Resolvable product video URL.",
    },
    thumbnailUrl: {
        type: "string",
        required: false,
        default: null,
        description: "Optional video thumbnail URL.",
    },
});

export const VARIANT_DOCUMENT_SHAPE = Object.freeze({
    _id: {
        type: "ObjectId",
        required: false,
        default: "generated by createVariant()",
        description: "MongoDB technical identifier for the variant document.",
    },
    productId: {
        type: "ObjectId",
        required: true,
        description: "Resolved parent product reference stored as a MongoDB ObjectId.",
    },
    sku: {
        type: "string",
        required: true,
        description:
            "Unique business key used for variant import, upsert, sync, and catalog lookup.",
    },
    variantAttributes: {
        type: "object",
        required: true,
        description:
            "Variant option values. RAM, ROM, and color live here and never inside product specs.",
    },
    ramSort: {
        type: "number",
        required: true,
        default: 0,
        description: "Variant RAM ordering hint for UI selection.",
    },
    romSort: {
        type: "number",
        required: true,
        default: 0,
        description: "Variant storage ordering hint for UI selection.",
    },
    colorPriority: {
        type: "number",
        required: true,
        default: 0,
        description: "Variant color ordering hint for UI selection.",
    },
    variantSortOrder: {
        type: "number",
        required: true,
        default: 0,
        description: "Overall variant ordering hint for UI selection.",
    },
    isPrimaryColor: {
        type: "boolean",
        required: true,
        default: false,
        description: "Marks the default color family when multiple color variants exist.",
    },
    originalPrice: {
        type: "number",
        required: true,
        description: "Original price for the variant.",
    },
    salePrice: {
        type: "number",
        required: true,
        description: "Sale price for the variant.",
    },
    currency: {
        type: "string",
        required: true,
        default: "VND",
        description: "Currency for originalPrice and salePrice.",
    },
    mediaIds: {
        type: "ObjectId[]",
        required: false,
        default: [],
        description:
            "Optional media metadata references associated with the variant gallery.",
        readonly: true,
    },
    video: {
        type: "object",
        required: false,
        default: null,
        description: "Optional variant video metadata.",
    },
    status: {
        type: "string",
        required: true,
        default: "active",
        enum: VARIANT_STATUSES,
        description: "Variant lifecycle status. Soft delete is tracked separately.",
    },
    isInStock: {
        type: "boolean",
        required: true,
        default: false,
        description: "Derived stock availability flag sourced from inventory-aware flows.",
        computed: true,
        denormalized: true,
        readonly: true,
    },
    createdAt: {
        type: "date",
        required: true,
        default: "generated by createVariant()",
        description: "Variant creation timestamp.",
    },
    updatedAt: {
        type: "date",
        required: true,
        default: "mirrors createdAt unless overridden",
        description: "Variant update timestamp.",
    },
    isDeleted: {
        type: "boolean",
        required: true,
        default: false,
        description: "Soft delete source-of-truth flag for the variant.",
    },
    deletedAt: {
        type: "date",
        required: false,
        default: null,
        description: "Soft delete timestamp. Null when isDeleted is false.",
    },
});

export function createVariant(input = {}) {
    const { createdAt, updatedAt } = createTimestampPair(input);
    const softDeleteState = createSoftDeleteState({
        isDeleted: input.isDeleted,
        deletedAt: input.deletedAt,
        fallbackDeletedAt: updatedAt,
    });
    const sku = normalizeRequiredString(normalizeSku(input.sku), "sku");
    const originalPrice = normalizeNonNegativeNumber(
        input.originalPrice,
        "originalPrice"
    );
    const salePrice = normalizeNonNegativeNumber(input.salePrice, "salePrice");

    assertVariantPricingInvariant({ originalPrice, salePrice });

    return {
        _id: createDocumentId(input._id, "_id"),
        productId: normalizeRequiredObjectId(input.productId, "productId"),
        sku,
        variantAttributes: createVariantAttributes(input.variantAttributes),
        ramSort: normalizeNonNegativeInteger(input.ramSort, "ramSort", 0),
        romSort: normalizeNonNegativeInteger(input.romSort, "romSort", 0),
        colorPriority: normalizeNonNegativeInteger(
            input.colorPriority,
            "colorPriority",
            0
        ),
        variantSortOrder: normalizeNonNegativeInteger(
            input.variantSortOrder,
            "variantSortOrder",
            0
        ),
        isPrimaryColor: normalizeBoolean(
            input.isPrimaryColor,
            "isPrimaryColor",
            false
        ),
        originalPrice,
        salePrice,
        currency: normalizeCurrency(input.currency),
        mediaIds: normalizeObjectIdList(input.mediaIds, "mediaIds"),
        video: createVariantVideo(input.video),
        status: normalizeVariantStatus(input.status),
        isInStock: normalizeBoolean(input.isInStock, "isInStock", false),
        createdAt,
        updatedAt,
        isDeleted: softDeleteState.isDeleted,
        deletedAt: softDeleteState.deletedAt,
    };
}

export function createVariantAttributes(input = {}) {
    if (typeof input !== "object" || input === null || Array.isArray(input)) {
        throw new Error("Catalog requires variantAttributes to be a plain object");
    }

    const colorFullName = normalizeOptionalString(
        input.colorFullName,
        "variantAttributes.colorFullName"
    );

    return {
        ram: normalizeRequiredString(input.ram, "variantAttributes.ram"),
        rom: normalizeRequiredString(input.rom, "variantAttributes.rom"),
        color: normalizeRequiredString(input.color, "variantAttributes.color"),
        ...(colorFullName ? { colorFullName } : {}),
    };
}

export function createVariantVideo(input) {
    if (input === undefined || input === null) {
        return null;
    }

    if (typeof input === "string") {
        return {
            url: normalizeRequiredString(input, "video.url"),
            thumbnailUrl: null,
        };
    }

    if (typeof input !== "object" || Array.isArray(input)) {
        throw new Error("Catalog requires video to be a string URL or a plain object");
    }

    return {
        url: normalizeRequiredString(input.url, "video.url"),
        thumbnailUrl: normalizeOptionalString(input.thumbnailUrl, "video.thumbnailUrl"),
    };
}

function normalizeCurrency(value) {
    return normalizeRequiredString(value ?? "VND", "currency");
}

function normalizeVariantStatus(value) {
    const normalizedStatus = value === undefined ? "active" : value;

    if (!VARIANT_STATUSES.includes(normalizedStatus)) {
        throw new Error(
            `Catalog variant status must be one of: ${VARIANT_STATUSES.join(", ")}`
        );
    }

    return normalizedStatus;
}
