export const AUTH_MODULE_NAME = "auth";
export const AUTH_BASE_PATH = "/auth";
export const AUTH_ACCESS_TOKEN_COOKIE_NAME = "auth_access_token";
export const AUTH_CUSTOMER_ACCESS_TOKEN_COOKIE_NAME =
    "customer_auth_access_token";
export const AUTH_ADMIN_ACCESS_TOKEN_COOKIE_NAME = "admin_auth_access_token";
export const AUTH_ACCESS_TOKEN_LIFETIME_MINUTES = process.env.AUTH_ACCESS_TOKEN_LIFETIME_MINUTES 
    ? parseInt(process.env.AUTH_ACCESS_TOKEN_LIFETIME_MINUTES, 10) 
    : 60;
export const AUTH_ACCESS_TOKEN_LIFETIME_SECONDS = AUTH_ACCESS_TOKEN_LIFETIME_MINUTES * 60;
export const AUTH_ACCESS_TOKEN_LIFETIME_MS =
    AUTH_ACCESS_TOKEN_LIFETIME_SECONDS * 1000;
export const AUTH_LOGIN_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const AUTH_LOGIN_RATE_LIMIT_MAX_ATTEMPTS = 5;
